In [1]:
import numpy as np
import scipy
import scipy.linalg

In [2]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]], float)

In [3]:
print(A)

[[ 1.  2.  3.]
 [ 2. 16. 21.]
 [ 4. 28. 73.]]


In [4]:
P, L, U = scipy.linalg.lu(A)

In [5]:
print(f'P: \n{P}')
print(f'L: \n{L}')
print(f'U: \n{U}')

P: 
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L: 
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U: 
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [6]:
b = np.array([4, 28, 94], float)

In [7]:
print(b)

[ 4. 28. 94.]


In [8]:
det_A = np.linalg.det(A)

In [9]:
print(np.round(det_A))

432.0


In [10]:
X = np.linalg.solve(A, b)

In [11]:
print(X)

[0.0462963  0.11574074 1.24074074]


In [12]:
print(np.dot(A, X))

[ 4. 28. 94.]
