In [1]:
import numpy as np

In [37]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]], float)
b = np.array([12, 2, 1], float)

In [38]:
print(A)

[[1. 2. 3.]
 [4. 0. 6.]
 [7. 8. 9.]]


In [39]:
print(b)

[12.  2.  1.]


In [40]:
det_A = np.linalg.det(A)

In [41]:
print(det_A)

59.999999999999986


In [42]:
# А не равно 0, решим СЛАУ

In [43]:
X1 = np.linalg.solve(A, b)
X2 = np.dot(np.linalg.inv(A), b)

In [44]:
print(X1)
print(X2)

[-9.2         0.9         6.46666667]
[-9.2         0.9         6.46666667]


In [45]:
print(np.dot(A, X1))
print(np.dot(A, X2))

[12.  2.  1.]
[12.  2.  1.]
