In [1]:
import numpy as np

In [25]:
v =np.array([1, 2, 3, 4])
F = np.array([v * 1, v * 2, v * 3, v * 4], float)

In [26]:
print(F)

[[ 1.  2.  3.  4.]
 [ 2.  4.  6.  8.]
 [ 3.  6.  9. 12.]
 [ 4.  8. 12. 16.]]


In [27]:
rank_F = np.linalg.matrix_rank(F)

In [28]:
print(rank_F)

1
