In [1]:
import numpy as np

In [14]:
M = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]], float)

In [15]:
print(M)

[[1. 2. 3.]
 [4. 0. 6.]
 [7. 8. 9.]]


In [16]:
det_M = np.linalg.det(M)

In [17]:
print(np.round(det_M, 0))

60.0
