In [1]:
import numpy as np
import scipy
import scipy.linalg

In [27]:
A = np.array([[1, 2, 3], [4, 5 ,6], [7, 8, 9]], float)
b = np.array([2, 5, 11])

In [28]:
print(A)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [29]:
print(b)

[ 2  5 11]


In [30]:
det_A = np.linalg.det(A)

In [31]:
print(np.round(det_A))

0.0


In [32]:
Q, R = np.linalg.qr(A)

In [33]:
print(f'Q: \n{Q}')
print(f'R: \n{R}')

Q: 
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
R: 
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]


In [34]:
R1 = R[:2, :2]

In [35]:
print(R1)

[[-8.1240384  -9.6011363 ]
 [ 0.          0.90453403]]


In [36]:
b1 = np.dot(Q.T, b)[:2]

In [37]:
print(b1)

[-1.21860576e+01  3.55271368e-15]


In [40]:
# Псевдорешение
X1 = np.append(np.linalg.solve(R1, b1), 0)

In [41]:
print(X1)

[1.50000000e+00 3.92767275e-15 0.00000000e+00]
