In [1]:
import numpy as np

In [18]:
G = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]], float)

In [19]:
print(G)

[[1. 2. 3.]
 [4. 0. 6.]
 [7. 8. 9.]]


In [20]:
G_inv = np.linalg.inv(G)

In [21]:
print(G_inv)

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


In [22]:
print(np.round(np.dot(G, G_inv), 0))

[[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]
