In [1]:
import numpy as np

In [46]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]], float)
b = np.array([1, 7, 12, 7, 15], float)

In [47]:
print(A)

[[ 1.  2. -1.]
 [ 3. -4.  0.]
 [ 8. -5.  2.]
 [ 2.  0. -5.]
 [11.  4. -7.]]


In [48]:
print(b)

[ 1.  7. 12.  7. 15.]


In [49]:
X = np.linalg.lstsq(A, b, rcond=None)[0]

In [50]:
print(X)

[ 1.13919353 -0.90498444 -0.9009803 ]


In [51]:
print(np.dot(A, X))

[ 0.23020495  7.03751834 11.83650981  6.78328855 15.21805313]
