In [1]:
import numpy as np

In [52]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], float)
b = np.array([[12, 2, 0]], float)

In [53]:
det_A = np.linalg.det(A)

In [54]:
print(np.round(det_A))

0.0


In [55]:
# А равно 0

In [56]:
# Считаем С

In [57]:
C = np.concatenate((A, b.T), axis=1)

In [58]:
print(C)

[[ 1.  2.  3. 12.]
 [ 4.  5.  6.  2.]
 [ 7.  8.  9.  0.]]


In [59]:
rank_A, rank_C = np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

In [60]:
print(rank_A, rank_C)

2 3


In [61]:
# У системы нет решения, так как ранг С больше чем ранг А

In [62]:
# Изменяем вектор b

In [69]:
b = np.array([[15, 16, 17]], float)

In [70]:
C = np.concatenate((A, b.T), axis=1)

In [71]:
print(C)

[[ 1.  2.  3. 15.]
 [ 4.  5.  6. 16.]
 [ 7.  8.  9. 17.]]


In [72]:
rank_A, rank_C = np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

In [73]:
print(rank_A, rank_C)

2 2


In [75]:
# Ранги А и С одинаковы, имеется хотябы одно решение

In [76]:
X = np.linalg.lstsq(A, b[0], rcond=None)[0]

In [77]:
print(X)

[-7.05555556  0.11111111  7.27777778]


In [78]:
print(np.dot(A, X))

[15. 16. 17.]
